# fly.toml app configuration file generated for teletwitch on 2023-11-01T22:38:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teletwitch"
primary_region = "sin"
swap_size_mb = 1024

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
